"""add run metadata and + run_citations

Revision ID: 684cf231160e
Revises: bfdbc1f75cf8
Create Date: 2025-12-31 21:09:26.994487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '684cf231160e'
down_revision: Union[str, Sequence[str], None] = 'bfdbc1f75cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_citations',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['runs.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id', 'rank', name='run_citations_pkey'),
    sa.UniqueConstraint('trace_id', 'chunk_id', name='rc_trace_id_chunk_id_key')
    )
    op.create_index('rc_trace_id_idx', 'run_citations', ['trace_id'], unique=False)
    op.add_column('runs', sa.Column('question_text', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('citations_mode', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('top_k', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('min_score', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('no_evidence', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'no_evidence')
    op.drop_column('runs', 'min_score')
    op.drop_column('runs', 'top_k')
    op.drop_column('runs', 'citations_mode')
    op.drop_column('runs', 'question_text')
    op.drop_index('rc_trace_id_idx', table_name='run_citations')
    op.drop_table('run_citations')
    # ### end Alembic commands ###
