"""add artifact dedupe fields

Revision ID: bf0c2049ee11
Revises: c72548ccde06
Create Date: 2025-12-28 01:23:21.581911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'bf0c2049ee11'
down_revision: Union[str, Sequence[str], None] = 'c72548ccde06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('file_hash', sa.Text(), nullable=True))
    op.add_column('artifacts', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'file_size')
    op.drop_column('artifacts', 'file_hash')
    # ### end Alembic commands ###
