"""add chunk hash and artifact metadata

Revision ID: bfdbc1f75cf8
Revises: bf0c2049ee11
Create Date: 2025-12-28 19:25:36.814368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfdbc1f75cf8'
down_revision: Union[str, Sequence[str], None] = 'bf0c2049ee11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('ingestion_stage', sa.Text(), nullable=True))
    op.add_column('artifacts', sa.Column('chunker_name', sa.Text(), nullable=True))
    op.add_column('artifacts', sa.Column('chunker_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('artifacts', sa.Column('embed_model', sa.Text(), nullable=True))
    op.create_check_constraint(
        'artifacts_ingestion_stage_check',
        'artifacts',
        "ingestion_stage IN ('extract','chunk','embed')",
    )
    op.add_column('chunks', sa.Column('chunk_hash', sa.Text(), nullable=True))
    op.create_index('chunks_artifact_id_chunk_hash_idx', 'chunks', ['artifact_id', 'chunk_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chunks_artifact_id_chunk_hash_idx', table_name='chunks')
    op.drop_column('chunks', 'chunk_hash')
    op.drop_constraint('artifacts_ingestion_stage_check', 'artifacts', type_='check')
    op.drop_column('artifacts', 'embed_model')
    op.drop_column('artifacts', 'chunker_params')
    op.drop_column('artifacts', 'chunker_name')
    op.drop_column('artifacts', 'ingestion_stage')
    # ### end Alembic commands ###
